server:
  port: 8088
  shutdown: graceful
  servlet:
    context-path: /eshop
spring:
  application:
    name: service-api-eshop


header:
  author:
    key-token: x-access-token
    value-token: ${ACCESS_TOKEN:ackoi$@lQAEkadjfoaj$ad12}