server:
  port: 8088
  shutdown: graceful
  servlet:
    context-path: /eshop
spring:
  application:
    name: service-api-eshop
  profiles:
    active: dev

management:
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: health,info,prometheus

